services:
  - type: web
    name: clyptus-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: clyptus-postgres
          property: connectionString
      - key: FRONTEND_ORIGINS
        value: https://clyptus-frontend.onrender.com

  - type: static
    name: clyptus-frontend
    env: static
    buildCommand: |
      cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: VITE_API_URL
        value: https://clyptus-backend.onrender.com


databases:
  - name: clyptus-postgres
    databaseName: recruitment_db
    user: clyptus_user
    plan: free
    region: oregon
